services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bitscoder
      - MONGO_INITDB_ROOT_PASSWORD=bitscoder
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bitscoder
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bitscoder
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=bitscoder
      - ME_CONFIG_BASICAUTH_PASSWORD==-098

volumes:
  mongo: {}
